Enhancements
VR-GMod/VirtualRoleplay pull request #13
Opened 2020-12-30 20:11 UTC by Nogitsu

Please take a look at it in priority.
Needed for modules and could be usefull for gamemode's based addons.

2020-12-30 20:29 UTC, Guthen requested changes

2020-12-30 20:29 UTC, Guthen commented on gamemodes/virtualroleplay/gamemode/modules/language/sh_language.lua
> +    if VRP.Languages[name][id] then
I think we should allow override of language phrases, in any case, developpers could find an easy workaround so you should get ride of this.

2020-12-30 21:15 UTC, Guthen approved these changes

2020-12-31 17:25 UTC, Erlite approved these changes

2020-12-31 17:25 UTC, merged