🚪 Property: initialize
VR-GMod/VirtualRoleplay pull request #16
Opened 2020-12-31 21:03 UTC by Guthen

2020-12-31 21:04 UTC, Erlite commented
Fix the conflicts please

2020-12-31 21:13 UTC, Erlite requested changes
Needs changes to how the networking is done, and a minor optimization tweak

2020-12-31 21:13 UTC, Erlite commented on gamemodes/virtualroleplay/entities/weapons/vrp_keys.lua
> +        net.WriteUInt( 1, 1 )
Just use WriteBit in that case

2020-12-31 21:13 UTC, Erlite commented on gamemodes/virtualroleplay/entities/weapons/vrp_keys.lua
> +        net.WriteUInt( 0, 1 )
Ditto

2020-12-31 21:13 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/libraries/sh_util.lua
> +function VRP.NetworkReceiveAsMethods( uint_bytes, methods )
One net message per function, no "shortcuts". This is a bad habit.

2020-12-31 21:13 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/property/cl_property.lua
> +net.Receive( "VRP:Property", VRP.NetworkReceiveAsMethods( 3, {
Ditto for the different functions for the received byte.

2020-12-31 21:13 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/property/sh_property.lua
> +    if ent:GetPos():Distance( self:GetPos() ) > 74 then return end
Replace with 
```lua
if ent:GetPos():DistToSqr( self:GetPos() ) > 5476 then return end
```
Reason being squared distance is more optimized.

2020-12-31 21:13 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/property/sv_property.lua
> +net.Receive( "VRP:Property", VRP.NetworkReceiveAsMethods( 3, {
Ditto

2020-12-31 21:13 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/property/sv_property.lua
> +        net.WriteTable( {
Write table is a sin, replace if possible.

2020-12-31 21:13 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/property/sv_property.lua
> +        net.WriteTable( self.vrp_keys[#self.vrp_keys] )
Ditto

2020-12-31 21:13 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/util/sh_notification.lua
> +    function VRP.Notify( text, type, length )
Add sanity checks to the data received just in case.

2021-01-01 16:31 UTC, Erlite approved these changes
lgtm

2021-01-01 19:31 UTC, Nogitsu commented
When buying a door from a double door it should buy the other.

2021-01-01 19:41 UTC, Nogitsu approved these changes
Everything looks good, merging.

2021-01-01 19:48 UTC, merged

2021-01-01 19:59 UTC, Guthen commented
> When buying a door from a double door it should buy the other.

I don't know if I could do something about that except the thing I said in the issue #17, but it will be manually fixed.