Hud reworked
VR-GMod/VirtualRoleplay pull request #18
Opened 2021-01-01 20:30 UTC by Nogitsu

2021-01-01 20:33 UTC, Erlite commented
Fix the conflicts

2021-01-01 20:42 UTC, Nogitsu commented
Has to be fixed

2021-01-01 20:57 UTC, Guthen requested changes

2021-01-01 20:57 UTC, Guthen commented on gamemodes/virtualroleplay/gamemode/modules/language/defs/sh_en.lua
> -
You just removed all the language from the property system, abort the language files changes.

2021-01-01 20:57 UTC, Guthen commented on gamemodes/virtualroleplay/gamemode/modules/hud/cl_hud.lua
> +    local y = ScrH() - h - 10
At first look, the HUD isn't responsive.

2021-01-01 20:58 UTC, Nogitsu commented on gamemodes/virtualroleplay/gamemode/modules/language/defs/sh_en.lua
> -
I copied the main's one 🤔
I'll try to see how to abord file changes (or reset my local branch)

2021-01-01 20:59 UTC, Nogitsu commented on gamemodes/virtualroleplay/gamemode/modules/hud/cl_hud.lua
> +    local y = ScrH() - h - 10
It isn't, I thought that it would change the ratio too much

2021-01-01 21:32 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/language/defs/sh_en.lua
> -
>:[

2021-01-04 10:10 UTC, Guthen approved these changes
Seems good, still need responsive

2021-01-05 16:44 UTC, Erlite approved these changes
lgtm

2021-01-05 16:45 UTC, merged