🍖 Hunger : Init
VR-GMod/VirtualRoleplay pull request #7
Opened 2020-12-28 19:56 UTC by Cobbrou

2020-12-28 19:59 UTC, Guthen requested changes
See above

2020-12-28 20:00 UTC, Guthen approved these changes

2020-12-28 22:13 UTC, Nogitsu commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +timer.Create("HungerThink", VRP.HungerStarvingTime, 0, HungerThink)
Why are you creating a local function for a one time use ?

2020-12-28 22:14 UTC, Nogitsu commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +function PLAYER:HungerUpdate()
Same than before, this function doesn't need to be in the meta, it's a one-time use, only in your "local timer", so you could copy the content direclty in your loop

2020-12-29 21:50 UTC, Nogitsu commented
Edited and approved (still need more reviews to confirm my edits)

2020-12-29 21:50 UTC, Nogitsu reviewed
Edited and approved (still need more reviews to confirm my edits)

2020-12-29 21:52 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +timer.Create("HungerThink", VRP.HungerStarvingTime, 0, HungerThink)
That's fine, I do that too sometimes, cleaner.

2020-12-29 21:53 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +function PLAYER:HungerUpdate()
That might actually prove useful for modding.

2020-12-29 21:54 UTC, Nogitsu commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +function PLAYER:HungerUpdate()
I can't see how modding can be usefull in the hunger's case

2020-12-29 21:55 UTC, Erlite requested changes
Few changes needed

2020-12-29 21:55 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +    return ( "You set your hunger to %s!" ):format( amount )
Might be cleaner to do 
```lua
return string.format( "You set your hunger to %s!", amount )
```

2020-12-29 21:55 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +    return ( "You reset your hunger!" )
Redundant parentheses
```lua
return "You reset your hunger!"
```

2020-12-29 21:56 UTC, Guthen commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +    return ( "You set your hunger to %s!" ):format( amount )
I prefer the way it's already done

2020-12-29 21:57 UTC, Nogitsu commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +    return ( "You set your hunger to %s!" ):format( amount )
Same

2020-12-29 21:57 UTC, Erlite commented on gamemodes/virtualroleplay/gamemode/modules/hunger/sv_hunger.lua
> +    return ( "You set your hunger to %s!" ):format( amount )
Not as clean or readable, but sure.

2020-12-30 13:19 UTC, Guthen approved these changes
Good, after the merge you should use the new language system for the chat commands. Also, you should remove the parentheses as said Erlite (but actually it should be gone after the language system implementation).

2020-12-30 18:36 UTC, Nogitsu approved these changes

2021-01-01 20:12 UTC, Erlite approved these changes

2021-01-01 20:13 UTC, merged